json.id place.id
json.trip_id place.trip_id
json.address place.address
json.name place.name
json.description place.description
json.image_url place.image_url
json.start_time place.start_time
json.end_time place.end_time
json.created_at place.created_at
json.updated_at place.updated_at